### ISSUE TITLE
attribute levels with comma invalidate the use of the function makeDesign()

### ISSUE THREAD

**Issue by albertostefanelli** [astrezhnev/conjointsdt#1]
Hi, 

thanks for the wonderful work. I spotted a small annoyance in the latest version of conjointsdt. Level attributes that have a comma are not properly parsed by the function makeDesign() of the cjoint package. The reason is that the .dat exported by conjointsdt file uses as delimitator commas. I suggest changing the comma with a special character and warn against its use.

**Comment by astrezhnev** [comment]
Thanks for noting this! Another workaround is just to define the design directly in R using makeDesign() since all that the .dat file does is pass along the probabilities and constraints (which can be set up manually in makeDesign() itself).
